import LegalLayout from "@/components/LegalLayout";

export const metadata = {
  title: "Terms of Service | CYPHER",
};

export default function TermsOfService() {
  return (
    <LegalLayout title="Terms of Service" lastUpdated="July 19, 2026">
      <p>
        By using CYPHER, you agree to the terms below. If you do not agree, please do not use the
        service.
      </p>

      <h2>What CYPHER is</h2>
      <p>
        CYPHER is an AI-powered study tool that generates personalized learning sessions for
        cybersecurity and IT topics, including a study plan, a knowledge check, key takeaways, an
        analyst tip, and a project scenario. All content is generated by an AI model in response to
        what you enter.
      </p>

      <h2>Not professional advice</h2>
      <p>
        Content generated by CYPHER is for educational and study purposes only. It is not a
        substitute for official certification training, professional security guidance, or advice
        from a qualified practitioner. AI generated content can be incomplete or contain errors.
        Always verify anything security or career critical against authoritative sources.
      </p>

      <h2>Acceptable use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>Attempt to overwhelm, abuse, or disrupt the service (including bypassing rate limits)</li>
        <li>Submit content intended to manipulate the underlying AI model into producing harmful output</li>
        <li>Use the service for any unlawful purpose</li>
      </ul>

      <h2>Your inputs, and what you get back</h2>
      <p>
        The topic, level, time, and goal you enter belong to you. The study session generated for
        you is yours to use freely, including as portfolio work, study material, or personal notes.
        We claim no ownership over content generated for your specific session.
      </p>

      <h2>No warranty</h2>
      <p>
        CYPHER is provided &quot;as is,&quot; without warranties of any kind, express or implied. We do not
        guarantee the service will be uninterrupted, error free, or that generated content will be
        entirely accurate.
      </p>

      <h2>Limitation of liability</h2>
      <p>
        To the fullest extent permitted by law, CYPHER and its creator are not liable for any
        indirect, incidental, or consequential damages arising from your use of the service,
        including reliance on any AI generated content.
      </p>

      <h2>Changes to the service or these terms</h2>
      <p>
        This is an actively developed personal project. Features may change, and these terms may be
        updated as the service evolves. Continued use after an update means you accept the revised
        terms.
      </p>

      <h2>Contact</h2>
      <p>
        Questions about these terms can be sent to{" "}
        <a href="mailto:info.cyph3r@gmail.com" className="font-semibold">our support email</a>.
      </p>
    </LegalLayout>
  );
}
